language: python
dist: trusty
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -e .[test]"
# command to run tests
script: 
# pytest --cov libsasscompiler tests/compile.py
  - coverage run --source=aiohttp_sample setup.py test
after_success:
  coveralls
