language: python
dist: trusty
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -e .[test]"
# command to run tests
services: mongodb
script: 
# pytest --cov libsasscompiler tests/compile.py
  - coverage run --source=app setup.py test
after_success:
  coveralls
env:
  - MONGO_URI=mongodb://mongodb:27017/ MONGO_DB=aiohttp_sample
